# Generated by Django 3.1.5 on 2021-02-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('useremail', models.EmailField(max_length=30, primary_key=True, serialize=False, verbose_name='아이디')),
                ('username', models.CharField(max_length=12, verbose_name='사용자')),
                ('password', models.CharField(max_length=12, verbose_name='비밀 번호')),
            ],
        ),
    ]
